% [V0,F0] = load_mesh('dragon-S10k.off');
% levels = floor(2.^((-14:2:-2)/3)*size(F0,1));
% [cages_V,cages_F,~,~,~,timing] = ...
% multires_per_layer( ...
% V0,F0, levels,...
% 'QuadratureOrder',2, ...
% 'ExpansionEnergy','displacement_path', ...
% 'FinalEnergy','volume', ...
% 'BetaInit',1e-2, ...
% 'EpsExpansion',2e-3,...
% 'EpsFinal',2e-4);
% % Obs.: Infinity flow didn't work

% [V0,F0] = load_mesh('dragon-1k.off');
% levels = floor(2.^((-14:2:-2)/3)*size(F0,1));
% [cages_V,cages_F,~,~,~,timing] = ...
% multires_per_layer( ...
% V0,F0, levels,...
% 'QuadratureOrder',2, ...
% 'ExpansionEnergy','displacement_path', ...
% 'FinalEnergy','volume', ...
% 'BetaInit',1e-2, ...
% 'EpsExpansion',2e-3,...
% 'EpsFinal',2e-4);
% % Obs.: Infinity flow didn't work

% [V0,F0] = load_mesh('happy_30k.off');
% clear V_coarse;
% clear F_coarse;
% [V_coarse{1},F_coarse{1}] = load_mesh('happy_30k_input_1.off');
% [V_coarse{1},F_coarse{1}] = meshfix(V_coarse{1},F_coarse{1});
% [cages_V,cages_F,~,~,~,timing] = ...
% multires_per_layer( ...
% V0,F0, [0],...
% 'QuadratureOrder',2, ...
% 'ExpansionEnergy','displacement_path', ...
% 'FinalEnergy','volume', ...
% 'BetaInit',1e-2, ...
% 'EpsExpansion',2e-3,...
% 'EpsFinal',2e-4,...
% 'V_coarse',V_coarse,'F_coarse',F_coarse);
% % Obs.: Infinity flow didn't work

% [V0,F0] = load_mesh('raptor-S20K.off');
% clear V_coarse;
% clear F_coarse;
% [V_coarse{1},F_coarse{1}] = load_mesh('raptor-S20K_input_1.off');
% [V_coarse{1},F_coarse{1}] = meshfix(V_coarse{1},F_coarse{1});
% [cages_V,cages_F,~,~,~,timing] = ...
% multires_per_layer( ...
% V0,F0, [0],...
% 'QuadratureOrder',2, ...
% 'ExpansionEnergy','displacement_path', ...
% 'FinalEnergy','volume', ...
% 'BetaInit',1e-2, ...
% 'EpsExpansion',2e-3,...
% 'EpsFinal',2e-4,...
% 'V_coarse',V_coarse,'F_coarse',F_coarse);
% % Obs.: Infinity flow didn't work

% [V0,F0] = load_mesh('raptor-1K.off');
% clear V_coarse;
% clear F_coarse;
% [V_coarse{1},F_coarse{1}] = load_mesh('raptor-1K_input_1.off');
% [V_coarse{1},F_coarse{1}] = meshfix(V_coarse{1},F_coarse{1});
% [cages_V,cages_F,~,~,~,timing] = ...
% multires_per_layer( ...
% V0,F0, [0],...
% 'QuadratureOrder',2, ...
% 'ExpansionEnergy','displacement_path', ...
% 'FinalEnergy','volume', ...
% 'BetaInit',1e-2, ...
% 'EpsExpansion',2e-3,...
% 'EpsFinal',2e-4,...
% 'V_coarse',V_coarse,'F_coarse',F_coarse);
% % Obs.: Infinity flow didn't work

% [V0,F0] = load_mesh('iwires-alien-19k.off');
% clear V_coarse;
% clear F_coarse;
% [V_coarse{1},F_coarse{1}] = load_mesh('iwires-alien-19k_input_1.off');
% [V_coarse{1},F_coarse{1}] = meshfix(V_coarse{1},F_coarse{1});
% [cages_V,cages_F,~,~,~,timing] = ...
% multires_per_layer( ...
% V0,F0, [0],...
% 'QuadratureOrder',2, ...
% 'ExpansionEnergy','displacement_path', ...
% 'FinalEnergy','volume', ...
% 'BetaInit',1e-2, ...
% 'EpsExpansion',2e-3,...
% 'EpsFinal',2e-4,...
% 'V_coarse',V_coarse,'F_coarse',F_coarse);
% % Obs.: Infinity flow didn't work

% [V0,F0] = load_mesh('Model5_10k.off');
% levels = floor(2.^((-14:2:-2)/3)*size(F0,1));
% [cages_V,cages_F,~,~,~,timing] = ...
% multires_per_layer( ...
% V0,F0, levels,...
% 'QuadratureOrder',2, ...
% 'ExpansionEnergy','displacement_path', ...
% 'FinalEnergy','volume', ...
% 'BetaInit',1e-2, ...
% 'EpsExpansion',2e-3,...
% 'EpsFinal',2e-4);
% % Obs.: Infinity flow didn't work

% [V0,F0] = load_mesh('Model5_1k.off');
% levels = floor(2.^((-14:2:-2)/3)*size(F0,1));
% [cages_V,cages_F,~,~,~,timing] = ...
% multires_per_layer( ...
% V0,F0, levels,...
% 'QuadratureOrder',2, ...
% 'ExpansionEnergy','displacement_path', ...
% 'FinalEnergy','volume', ...
% 'BetaInit',1e-2, ...
% 'EpsExpansion',2e-3,...
% 'EpsFinal',2e-4);
% % Obs.: Infinity flow didn't work

% [V0,F0] = load_mesh('Model11_fixed.obj');
% levels = floor(2.^((-14:2:-2)/3)*size(F0,1));
% [cages_V,cages_F,~,~,~,timing] = ...
% multires_per_layer( ...
% V0,F0, levels,...
% 'QuadratureOrder',2, ...
% 'ExpansionEnergy','displacement_path', ...
% 'FinalEnergy','volume', ...
% 'BetaInit',1e-2, ...
% 'EpsExpansion',2e-3,...
% 'EpsFinal',2e-4);
% % Obs.: Infinity flow didn't work

% [V0,F0] = load_mesh('Model11_3k.off');
% levels = floor(2.^((-14:2:-2)/3)*size(F0,1));
% [cages_V,cages_F,~,~,~,timing] = ...
% multires_per_layer( ...
% V0,F0, levels,...
% 'QuadratureOrder',2, ...
% 'ExpansionEnergy','displacement_path', ...
% 'FinalEnergy','volume', ...
% 'BetaInit',1e-2, ...
% 'EpsExpansion',2e-3,...
% 'EpsFinal',2e-4);
% % Obs.: Infinity flow didn't work